#pragma config(Sensor, dgtl1,  RightBase,      sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  LeftBase,       sensorQuadEncoder)
#pragma config(Motor,  port1,           LClaw,         tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           LeftFront,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           RightFront,    tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           RightLift,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           LeftLift,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           LeftBack,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           RightBack,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           LTower,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           RTower,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          RClaw,         tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}
void SetRight(int power)
{
	motor[RightFront] = motor[LeftFront] = power;
}
void SetLeft(int power)
{
	motor[LeftFront] = motor[LeftBack] = power;
}
void Stop(int time)
{
	motor[LeftFront] = motor[LeftBack] = motor[RightFront] = motor[RightBack] = 0;
	wait1Msec(time);
}
void Lift(int power, int time)
{
	motor[RightLift] = motor[LeftLift] = power;
	wait1Msec(time);
}
void LiftStop(int time)
{
	motor[RightLift] = motor[LeftLift] = 0;
	wait1Msec(time);
}
void SetBase(int power)
{
	motor[LeftFront] = motor[LeftBack] = motor[RightFront] = motor[RightBack] = power;
}
void RightPointTurn(int distance)
{
		while(abs(SensorValue[LeftBase]) < distance)
	{
		SetRight(-127);
		SetLeft(127);
	}
	SetBase(0);
}
void LeftPointTurn(int distance)
{
		while(abs(SensorValue[RightBase])<distance)
	{
		SetRight(127);
		SetLeft(-127);
	}
	SetBase(0);
}
void TowerRise(int power, int time)
{
	motor[RTower] = motor[LTower]  = power;
	wait1Msec(time);
}
void TowerDown(int power, int time)
{
	motor[RTower] = motor[LTower]  = -power;
	wait1Msec(time);
}
void TowerStop(int time)
{
	motor[RTower] = motor[LTower] = 0;
	wait1Msec(time);
}

void Move(int power, int distance)
{
	SensorValue[LeftBase] = 0;
	SensorValue[RightBase] = 0;
	float kp = 0.5;//proportional constant, can be tuned.
	while(abs(SensorValue[RightBase]+SensorValue[LeftBase])/2 < distance)
		{
			int error = SensorValue[LeftBase] - SensorValue[RightBase];
			//find the difference between the two encoders.
			SetLeft(power - error*kp);
			SetRight(power + error*kp);
		}//end while
		SetRight(0);
		SetLeft(0);
	}// end MoveForward
void Claw(int power, int time)
{
	motor[LClaw] = motor[RClaw] = power;
	wait1Msec(time);
}
void Set(int power, int time)
{
	SetBase(power);
	wait1Msec(time);
}
/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/
task autonomous()
{
	wait1Msec(10);							// Robot waits for 200 milliseconds before executing program
	TowerRise(127, 800);
  TowerStop(10);
  Lift(127, 1520);
	LiftStop(10);
	Set(127, 1500);
	Stop(200);
	Lift(-127, 1450);
	LiftStop(100);

	// ..........................................................................
	// Insert user code here.
	// ..........................................................................

	// Remove this function call once you have "real" code.
	AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	// User control code here, inside the loop
	while (true)
	{
		motor[RightFront] = motor[RightBack] = vexRT(Ch2);//combine Right motors all forward.	`````````
		motor[LeftBack] = motor[LeftFront] = vexRT(Ch3);//combine Left Motors all forward.
		if(vexRT[Btn6U] == 1)
		{
			motor[RightLift] = motor[LeftLift] = 127;
		}
		else if(vexRT[Btn6D] == 1)
		{
			motor[RightLift] = motor[LeftLift] = -127;
		}
		else
		{
			motor[RightLift] = motor[LeftLift] = 0;
		}

		if(vexRT[Btn5U] ==1)
		{
			motor[RTower] = motor[LTower] = 127;
		}
		else if(vexRT[Btn5D] == 1)
		{
			motor[RTower] = motor[LTower] = -127;
		}
		else
		{
			motor[RTower] = motor[LTower] = 0;
		}
		if(vexRT[Btn8U] == 1)
		{
			motor[LClaw] = motor[RClaw] = 127;
		}
		else if(vexRT[Btn7U] == 1)
		{
			motor[LClaw] = motor[RClaw] = -127;
		}
		else
		{
				motor[LClaw] = motor[RClaw] = 0;
		}

		// This is the main execution loop for the user control program.
		// Each time through the loop your program should update motor + servo
		// values based on feedback from the joysticks.

		// ........................................................................
		// Insert user code here. This is where you use the joystick values to
		// update your motors, etc.
		// ........................................................................

		// Remove this function call once you have "real" code.
		UserControlCodePlaceholderForTesting();
	}
}
