#pragma config(Motor,  port7,           righttower,    tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           lefttower,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           righttower1,   tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          lefttower1,    tmotorVex393HighSpeed_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
motor[righttower] = -127;
motor[lefttower] = -127;
motor[righttower1] = 127;
motor[lefttower1] = 127;
wait1Msec(3000);
motor[righttower] = 0;
motor[lefttower] = 0;
motor[righttower1] = 0;
motor[lefttower1] = 0;
wait1Msec(2000);
motor[righttower] = 127;
motor[lefttower] = 127;
motor[righttower1] = -127;
motor[lefttower1] = -127;
wait1Msec(3000);

}
