#pragma config(Motor,  port1,           RightFront,    tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           LeftFront,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           Rightback,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           Leftback,      tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/
void setleftdrive(int power)
{ motor[LeftFront]= power;
	motor[Leftback] = power;
}

void setrightdrive(int power)
{motor[RightFront] = power;
	motor[Rightback] = power;

}



void driveforward( int power = 127, int time)
{
	setrightdrive(127);
	setleftdrive(127);
	wait1Msec(time);
	setrightdrive(0);
	setleftdrive(0);
}
void drivebackward(int power, int time)
{
	setrightdrive(127);
	setleftdrive(127);
	wait1Msec(time) ;
	setrightdrive(0);
	setleftdrive(0);

}
void turnleft( int time,int power= 127)
{
	setrightdrive(power);
	setleftdrive(-power);
	wait1Msec(time) ;
	setrightdrive(0);
	setleftdrive(0);
}
void turnright(int time, int power = 127)

{
	setrightdrive(-power);
	setleftdrive(power);
	wait1Msec(time) ;
	setrightdrive(0);
	setleftdrive(0);

}

#define Left 1
#define Right 0
void turn(int direction,int power,int time)
{
	if (direction == Left)
	{
		turnleft(time,power);
	}
	else if (direction == Right)
	{
		turnright(time,power);

	}

}



task autonomous()
{ //1
	//motor[RigthFrontmotor] = 127;
	//motor[LeftFrontmotor] = 127;
	//motor[Rightbackmotor] = 127;
	// same as motor[RigthFrontmotor] = motor[LeftFrontmotor] = motor[Rightbackmotor]= 127;
	driveforward(127,5000);
	drivebackward(-127,5000);
	turn(Left,127,3000);
	turn(Right,127,3000);

	motor[RightFront] = motor[Rightback] = 127;
	motor[LeftFront] = motor[Leftback] = 127;
	wait1Msec(1000) ;
	motor[RightFront] = 	motor[Rightback] = 0;
	motor[LeftFront] = motor[Leftback] = 0;
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/
void setArm(int power)
{
	motor[LA] = motor[RA] = power;
}
task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{
		if (vexRT[Btn5U] == 1)
		{
			setArm(127);
		}
		else if(vexRT[Btn5D] == 1)
		{
			setArm(-127);
		}
		else
		{
			setArm(0);
		}

		if(vexRT[Ch3] >20 ||vexRT[Ch3]<-20)//this code is to make the motor not running when we didnt press any button
		{ setleftdrive(vexRT[Ch3]);

		}
		else
		{
			setleftdrive(0);


		}
		if(vexRT[Ch2] >20 ||vexRT[Ch2]<-20)
		{
			setrightdrive(vexRT[Ch2]);

		}
		else
		{
			setrightdrive(0);

		}

	// This is the main execution loop for the user control program.
		// Each time through the loop your program should update motor + servo
		// values based on feedback from the joysticks.

		// ........................................................................
		// Insert user code here. This is where you use the joystick values to
		// update your motors, etc.
		// ........................................................................

		// Remove this function call once you have "real" code.
		UserControlCodePlaceholderForTesting();
	}
}
