#pragma config(Sensor, in1,    RTower,         sensorPotentiometer)
#pragma config(Sensor, in2,    Gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  REncoder,       sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  LEncoder,       sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  LCD1,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl6,  LCD2,           sensorLEDtoVCC)
#pragma config(Motor,  port1,           RClaw,         tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           RFront,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           LFront,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           RLift,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           LLift,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           RBack,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           LBack,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           LTower,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           RTower,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          LClaw,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
  // ..........................................................................
  // Insert user code here.
  // ..........................................................................

  // Remove this function call once you have "real" code.
  AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
  // User control code here, inside the loop

  while (true)
  {
  	motor[RFront] = motor[RBack] = vexRT(Ch2) - vexRT(Ch1);//combine Right Motors all forward.
		motor[LBack] = motor[LFront] = vexRT(Ch2) + vexRT(Ch1);//combine Left Motors all forward.
		motor[RFront] = motor[RBack] = vexRT(Ch2);//combine Right motors all forward.	`````````
		motor[LBack] = motor[LFront] = vexRT(Ch3);
		if(vexRT[Btn5U] == 1)
		{
			motor[RLift] = motor[LLift] = 127;
		}
		else if(vexRT[Btn5D] == 1)
		{
			motor[RLift] = motor[LLift] = -127;
		}
		else
		{
			motor[RLift] = motor[LLift] = 0;
		}
		if(vexRT[Btn6U] ==1)
		{
			motor[RTower] = motor[LTower] = 127;
		}
		else if(vexRT[Btn6D] == 1)
		{
			motor[RTower] = motor[LTower] = -127;
		}
		else
		{
			motor[RTower] = motor[LTower] = 0;
		}
		if(vexRT[Btn7L] == 1)
		{
			motor[RClaw] = motor[LClaw] = 100;
		}
		else if(vexRT[Btn8R] == 1)
		{
			motor[RClaw] = motor[LClaw] = -100;
		}
		else
		{
				motor[RClaw] = motor[LClaw] = 0;
		}
    // This is the main execution loop for the user control program.
    // Each time through the loop your program should update motor + servo
    // values based on feedback from the joysticks.

    // ........................................................................
    // Insert user code here. This is where you use the joystick values to
    // update your motors, etc.
    // ........................................................................

    // Remove this function call once you have "real" code.
    UserControlCodePlaceholderForTesting();
  }
}
