#pragma config(Sensor, in1,    RTower,         sensorPotentiometer)
#pragma config(Sensor, dgtl1,  REncouder,      sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  LEncouder,      sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  LCD1,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl6,  LCD2,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl7,  LCD3,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl8,  LCD4,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl9,  LCD5,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl10, LCD6,           sensorLEDtoVCC)
#pragma config(Motor,  port1,           RClaw,         tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           RFront,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           LFront,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           RLift,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           LLift,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           Rback,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           Lback,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           LTower,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           RTower,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          LClaw,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/
/*===================================================================*\
| Initilize Global Variables..........................................|
|---------------------------------------------------------------------|
| these variables are used in methods that deal with auton all the    |
| way to decalaring variables for battery voltage                     |
\*===================================================================*/
//int statement used for numbers.
int myAutonomous = 10;

/*===================================================================*\
| Auton Names.........................................................|
|---------------------------------------------------------------------|
| declares the constant strings for the different auton names that    |
| are then displayed on the LCD display, also contains the open and   |
| close string for the claw method for easier use                     |
\*===================================================================*/
const string autonOne = "Skills";
const string autonTwo = "Red Right";
const string autonThree = "Red Left";
const string autonFour = "Blue Right";
const string autonFive = "Blue Left";
const string autonTest = "Test";
string open = "open";
string close = "close";

/*===================================================================*\
| LED.................................................................|
|---------------------------------------------------------------------|
| used in the 1010S task as an easy way to shut off all the           |
| lights                                                              |
\*===================================================================*/
void lightEmittingDiode (int power){
	SensorValue[LED1] = power;
	SensorValue[LED2] = power;
	SensorValue[LED3] = power;
	SensorValue[LED4] = power;
	SensorValue[LED5] = power;
	SensorValue[LED6] = power;
}

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

void SetRight(int power)
{
	motor[RFront] = motor[RBack] = power;
}

void SetLeft(int power)
{
	motor[LFront] = motor[LBack] = power;
}

/*===================================================================*\
| Resets Drive Encoder................................................|
|---------------------------------------------------------------------|
| sets the drive encoders to 0 to then be used throughout the methods |
\*===================================================================*/
void setDrive (int power){
	// resets encoder values to 0
	SensorValue(REncouder) = 0;
	SensorValue(LEncouder) = 0;
	motor[RFront] = motor[RBack] = motor[LFront] = motor[LBack] = power;
}

/*===================================================================*\
| Stop Drive..........................................................|
|---------------------------------------------------------------------|
| completly stops the drive motors, used in auton methods             |
\*===================================================================*/
void StopDrive()
{
	motor[RFront] = motor[LFront] = motor[RBack] = motor[LBack] = 0
}

/*===================================================================*\
| Stop Mobile Goal....................................................|
|---------------------------------------------------------------------|
| completly stops the mobile goal lift motors                         |
\*===================================================================*/
void StopLift()
{
	motor[RLift] = motor[LLift] = 0;
}

/*------------------------------------------------------------------*\
//	______      _
//	|  _  \    (_)
//	| | | |_ __ ___   _____
//	| | | | '__| \ \ / / _ \
//	| |/ /| |  | |\ V /  __/
//	|___/ |_|  |_| \_/ \___|
\*------------------------------------------------------------------*/

/*===================================================================*\
| Move..........................................................|
|---------------------------------------------------------------------|
| allows the use for timing when controling the drive, but also uses  |
| the drive straight commands                                         |
\*===================================================================*/
void Move(int power, int distance)
{
	SensorValue[LEncouder] = 0;
	SensorValue[REncouder] = 0;
	float kp = 0.5;//proportional constant, can be tuned.
	while(abs(SensorValue[REncouder]+SensorValue[LEncouder])/2 < distance)
		{
			int error = SensorValue[LEncouder] - SensorValue[REncouder];
			//find the difference between the two encoders.
			SetLeft(power - error*kp);
			SetRight(power + error*kp);
		}//end while
		SetRight(0);
		SetLeft(0);
	}// end MoveForward

void RightPointTurn(int distance)
{
		while(abs(SensorValue[LEncouder]) < distance)
	{
		SetRight(-127);
		SetLeft(127);
	}
	SetDrive(0);
}
void LeftPointTurn(int distance)
{
		while(abs(SensorValue[REncouder])<distance)
	{
		SetRight(127);
		SetLeft(-127);
	}
	SetDrive(0);
}

void TowerRise(int position)
{
	while(SensorValue[RTower] < position;
	{
	motor[RTower] = motor[LTower]  = 127;
	}

	motor[RTower] = motor[LTower] = 0;
}

void TowerDown(int position)
{
while(SensorValue[RTower] > position;
	{
	motor[RTower] = motor[LTower]  = -127;
	}

	motor[RTower] = motor[LTower] = 0;
}

void TowerStop(int time)
{
	motor[RTower] = motor[LTower] = 0;
	wait1Msec(time);
}

void Lift(int power, int time)
{
	motor[RLift] = motor[LLift] = power;
	wait1Msec(time);
}

void LiftStop(int time)
{
	motor[RLift] = motor{LLift] = 0;
	wait1Msec(time);
}

void Claw(int power, int time)
{
	motor[RClaw] = motor[LClaw] = power;
	wait1Msec(time);
}

/*------------------------------------------------------------------*\
// 	 _     ___________
//	| |   /  __ \  _  \
//	| |   | /  \/ | | |
//	| |   | |   | | | |
//	| |___| \__/\ |/ /
//	\_____/\____/___/
\*------------------------------------------------------------------*/

/*===================================================================*\
| Display LCD.........................................................|
|---------------------------------------------------------------------|
| displays the current auton that is selcted on the LCD               |
\*===================================================================*/
void displayLCD(){
	switch (myAutonomous)
	{
	case 0:
		displayLCDCenteredString(0, autonOne);displayLCDCenteredString(1, "Selected");break;
	case 1:
		displayLCDCenteredString(0, autonTwo);displayLCDCenteredString(1, "Selected");break;
	case 2:
		displayLCDCenteredString(0, autonThree);displayLCDCenteredString(1, "Selected");break;
	case 3:
		displayLCDCenteredString(0, autonFour);displayLCDCenteredString(1, "Selected");break;
	case 4:
		displayLCDCenteredString(0, autonFive);displayLCDCenteredString(1, "Selected");break;
	case 5:
		displayLCDCenteredString(0, autonSix);displayLCDCenteredString(1, "Selected");break;
	case 6;
	}
}


/*===================================================================*\
| Auton Setter........................................................|
|---------------------------------------------------------------------|
| sets the auton and shows the menu display to select an auton        |
\*===================================================================*/
void autoSetter (int value, bool select = false){
	clearLCDLine(0);
	clearLCDLine(1);
	// saves auton in gloabal variable
	if (select)
		myAutonomous = value;

	//displays set or select accordingly
	if(myAutonomous == value)
		displayLCDCenteredString(1, ">SET<");
	else
		displayLCDCenteredString(1, ">select<");

	// shows auton names
	switch(value)
	{
	case 0:
		displayLCDCenteredString(0, autonOne); break;
	case 1:
		displayLCDCenteredString(0, autonTwo); break;
	case 2:
		displayLCDCenteredString(0, autonThree); break;
	case 3:
		displayLCDCenteredString(0, autonFour); break;
	case 4:
		displayLCDCenteredString(0, autonFive); break;
	case 5:
		displayLCDCenteredString(0, autonTest); break;
	case 6;
	}
}

/*===================================================================*\
| Auton Selector......................................................|
|---------------------------------------------------------------------|
| the framework for being able to use the menu system on the LCD      |
\*===================================================================*/
void autoSelector(){
	// sets choice to 0
	int choice = 0;
	autoSetter(0);

	while (vexRT[Btn7U] != 1){
		if ((vexRT[Btn7L] == 1) || (vexRT[Btn7R] == 1)){
			// previous choice
			if (vexRT[Btn7L] == 1){
				if (--choice < 0){
					choice = 9;
				}
			}
			// next choice
			if (vexRT[Btn7R] == 1){
				if (++choice > 9){
					choice = 0;
				}
			}
			autoSetter(choice);
		}

		// select choice
		if (vexRT[Btn7D] == 1)
			autoSetter(choice, true);
		wait1Msec(120);
	}
	wait1Msec(200);
	return;
}

/*------------------------------------------------------------------*\
//	 _____         _
//	|_   _|       | |
//	  | | __ _ ___| | _____
//	  | |/ _` / __| |/ / __|
//	  | | (_| \__ \   <\__ \
//	  \_/\__,_|___/_|\_\___/
\*------------------------------------------------------------------*/

/*===================================================================*\
| Battery Voltage.....................................................|
|---------------------------------------------------------------------|
| calculates and displays the current battery voltage on the LCD      |
\*===================================================================*/
task batteryVoltage () // source http://www.robotc.net/blog/2012/05/18/advanced-applications-with-the-vex-lcd/
{
	while(true)                                                  // An infinite loop to keep the program running until you terminate it
	{
		clearLCDLine(0);                                            // Clear line 1 (0) of the LCD
		clearLCDLine(1);                                            // Clear line 2 (1) of the LCD

		//Display the Primary Robot battery voltage
		displayLCDString(0, 0, "Primary: ");
		sprintf(mainBattery, "%1.2f%c", nImmediateBatteryLevel/1000.0,'V'); //Build the value to be displayed
		displayNextLCDString(mainBattery);

		//Display the Backup battery voltage
		displayLCDString(1, 0, "Backup: ");
		sprintf(backupBattery, "%1.2f%c", BackupBatteryLevel/1000.0, 'V');    //Build the value to be displayed
		displayNextLCDString(backupBattery);

		//Short delay for the LCD refresh rate
		wait1Msec(100);
	}
	EndTimeSlice();
}

/*===================================================================*\
| 1010S...............................................................|
|---------------------------------------------------------------------|
| makes our cortex look cool                                          |
\*===================================================================*/
task 1010S (){
	while (true){
		lightEmittingDiode (0);
		SensorValue[LED1] = 1;
		wait1Msec(150);
		lightEmittingDiode (0);
		SensorValue[LED2] = 1;
		wait1Msec(150);
		lightEmittingDiode (0);
		SensorValue[LED3] = 1;
		wait1Msec(150);
		lightEmittingDiode (0);
		SensorValue[LED4] = 1;
		wait1Msec(150);
		lightEmittingDiode (0);
		SensorValue[LED5] = 1;
		wait1Msec(150);
		lightEmittingDiode (0);
		SensorValue[LED6] = 1;
		wait1Msec(150);
		lightEmittingDiode (0);
		SensorValue[LED7] = 1;
		wait1Msec(150);
		lightEmittingDiode (0);
		SensorValue[LED6] = 1;
		wait1Msec(150);
	}
	EndTimeSlice();
}

/*------------------------------------------------------------------*\
//	___  ___      _     _ _        _____             _
//	|  \/  |     | |   (_) |      |  __ \           | |
//	| .  . | ___ | |__  _| | ___  | |  \/ ___   __ _| |
//	| |\/| |/ _ \| '_ \| | |/ _ \ | | __ / _ \ / _` | |
//	| |  | | (_) | |_) | | |  __/ | |_\ \ (_) | (_| | |
//	\_|  |_/\___/|_.__/|_|_|\___|  \____/\___/ \__,_|_|
\*------------------------------------------------------------------*/

/*===================================================================*\
| Red.................................................................|
|---------------------------------------------------------------------|
| Done: none                                                          |
\*===================================================================*/
void RedRight()
{
	char Red_Right;

	//score preload on the mobile goal.
	startTask(TowerTask);
	TowerPosition = 700;
	wait1Msec(200);
	Lift(-127, 1400);
	LiftStop(10);
	Move(127, 500);
	StopDrive(300);
	Lift(127, 1400);
	TowerDown(0);
	TowerStop(100);
	Claw(127, 400);
	Move(-127, -400);
	LeftPointTurn(200);
	Move(80, 134);
	LeftPointTurn(130);
	Move(127, 240);
	TowerRise(300);
	Lift(-127; 1200);
	Move(-127, 200);
	StopDrive(100);
}






/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

int TowerHold = 1; //Tower loop flag
int TowerPosition = 0; // Position to set the tower

task TowerTask()
{
	TowerPosition = SensorValue[RTower];
	while(true)
	{
		if(TowerHold)//should tower code be running?
		{
			//calculate difference
		int difference = (SensorValue[RTower] - TowerPosition)*0.5;

		//Cap difference value if needed
		if(difference > 127)
			difference = 127;
		else if(difference < -127)
			difference = -127;

			motor[RTower] = motor[LTower] = difference;
		}
	}
}


task autonomous()
{
  // ..........................................................................
  // Insert user code here.
  // ..........................................................................

  // Remove this function call once you have "real" code.
  AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
  // User control code here, inside the loop

  while (true)
  {
    // This is the main execution loop for the user control program.
    // Each time through the loop your program should update motor + servo
    // values based on feedback from the joysticks.

    // ........................................................................
    // Insert user code here. This is where you use the joystick values to
    // update your motors, etc.
    // ........................................................................

    // Remove this function call once you have "real" code.
    UserControlCodePlaceholderForTesting();
  }
}
